#!/usr/bin/env node
/**
 * Ex Nihilo - Pipeline Reports Dashboard Server
 *
 * Serves HTML reports generated by scheduled Claude Code pipelines.
 * Periodically git-pulls to pick up reports pushed by remote agents.
 *
 * Usage: node reports/serve.js
 * Env:   PORT (default 8090), PULL_INTERVAL (ms, default 300000)
 */

const http = require('http');
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const PORT = parseInt(process.env.PORT || '8090', 10);
const PULL_INTERVAL = parseInt(process.env.PULL_INTERVAL || '300000', 10);
const REPO_ROOT = path.resolve(__dirname, '..');
const REPORTS_DIR = __dirname;

const PIPELINES = [
  { id: 'bugfix-playtest', name: 'Bug Fix & Playtest',      schedule: 'Daily 00:00 UTC', colour: '#10b981', icon: '\u{1F41B}' },
  { id: 'security',        name: 'Security Scan',            schedule: 'Daily 02:00 UTC', colour: '#f59e0b', icon: '\u{1F6E1}' },
  { id: 'feature-impl',    name: 'Feature Implementation',   schedule: 'Daily 04:00 UTC', colour: '#3b82f6', icon: '\u{2699}'  },
  { id: 'research',        name: '4X Game Research',          schedule: 'Daily 06:00 UTC', colour: '#8b5cf6', icon: '\u{1F52C}' },
];

// ── Git sync ────────────────────────────────────────────────────────────
function gitPull() {
  try {
    execSync('git pull --ff-only 2>&1', { cwd: REPO_ROOT, timeout: 30000 });
    console.log(`[${new Date().toISOString()}] git pull OK`);
  } catch (err) {
    console.error(`[${new Date().toISOString()}] git pull failed:`, err.message);
  }
}

// ── Report scanning ────────────────────────────────────────────────────
function getReports(pipelineId) {
  const dir = path.join(REPORTS_DIR, pipelineId);
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.html'))
    .sort()
    .reverse()
    .map(f => {
      const stat = fs.statSync(path.join(dir, f));
      return {
        file: f,
        date: f.replace('.html', ''),
        size: (stat.size / 1024).toFixed(1) + ' KB',
        mtime: stat.mtime.toISOString(),
      };
    });
}

// ── Dashboard HTML ─────────────────────────────────────────────────────
function renderDashboard() {
  const pipelineCards = PIPELINES.map(p => {
    const reports = getReports(p.id);
    const latest = reports[0];
    const reportRows = reports.slice(0, 14).map(r => `
      <tr>
        <td><a href="/${p.id}/${r.file}">${r.date}</a></td>
        <td>${r.size}</td>
        <td>${new Date(r.mtime).toLocaleString('en-GB', { timeZone: 'UTC' })}</td>
      </tr>`).join('');

    return `
    <div class="card" style="border-top: 3px solid ${p.colour}">
      <div class="card-header">
        <span class="card-icon">${p.icon}</span>
        <div>
          <h2>${p.name}</h2>
          <span class="schedule">${p.schedule}</span>
        </div>
        <span class="report-count">${reports.length} report${reports.length !== 1 ? 's' : ''}</span>
      </div>
      ${latest
        ? `<div class="latest">
            <span class="label">Latest:</span>
            <a href="/${p.id}/${latest.file}">${latest.date}</a>
            <span class="meta">(${latest.size})</span>
           </div>`
        : '<div class="latest empty">No reports yet</div>'
      }
      ${reports.length > 0
        ? `<details><summary>All reports</summary>
           <table>
             <thead><tr><th>Date</th><th>Size</th><th>Generated</th></tr></thead>
             <tbody>${reportRows}</tbody>
           </table>
           </details>`
        : ''
      }
    </div>`;
  }).join('');

  // Recent activity timeline (all pipelines merged)
  const allReports = PIPELINES.flatMap(p =>
    getReports(p.id).map(r => ({ ...r, pipeline: p }))
  ).sort((a, b) => b.mtime.localeCompare(a.mtime)).slice(0, 20);

  const timelineRows = allReports.map(r => `
    <tr>
      <td><span class="dot" style="background:${r.pipeline.colour}"></span> ${r.pipeline.name}</td>
      <td><a href="/${r.pipeline.id}/${r.file}">${r.date}</a></td>
      <td>${r.size}</td>
      <td>${new Date(r.mtime).toLocaleString('en-GB', { timeZone: 'UTC' })}</td>
    </tr>`).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Ex Nihilo - Pipeline Reports</title>
<meta http-equiv="refresh" content="60">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    background: #0a0e17;
    color: #c8d6e5;
    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
    line-height: 1.6;
  }
  .header {
    background: linear-gradient(135deg, #0f1729 0%, #1a1f3a 100%);
    border-bottom: 1px solid #1e2d3d;
    padding: 2rem;
    text-align: center;
  }
  .header h1 {
    color: #00d4ff;
    font-size: 2rem;
    font-weight: 300;
    letter-spacing: 0.1em;
  }
  .header .subtitle {
    color: #5a7a94;
    font-size: 0.9rem;
    margin-top: 0.3rem;
  }
  .container { max-width: 1400px; margin: 0 auto; padding: 2rem; }
  .grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
    gap: 1.5rem;
    margin-bottom: 3rem;
  }
  .card {
    background: #111827;
    border-radius: 8px;
    padding: 1.5rem;
    border: 1px solid #1e2d3d;
    transition: border-color 0.2s;
  }
  .card:hover { border-color: #2d4a5e; }
  .card-header {
    display: flex;
    align-items: center;
    gap: 1rem;
    margin-bottom: 1rem;
  }
  .card-icon { font-size: 2rem; }
  .card-header h2 { color: #e2e8f0; font-size: 1.1rem; font-weight: 600; }
  .schedule { color: #5a7a94; font-size: 0.8rem; }
  .report-count {
    margin-left: auto;
    background: #1a2332;
    padding: 0.3rem 0.7rem;
    border-radius: 12px;
    font-size: 0.8rem;
    color: #5ce0d8;
  }
  .latest { margin: 1rem 0; padding: 0.8rem; background: #0d1117; border-radius: 6px; }
  .latest.empty { color: #5a7a94; font-style: italic; }
  .label { color: #5a7a94; font-size: 0.85rem; margin-right: 0.5rem; }
  .meta { color: #5a7a94; font-size: 0.85rem; margin-left: 0.5rem; }
  a { color: #00d4ff; text-decoration: none; }
  a:hover { text-decoration: underline; }
  details { margin-top: 0.5rem; }
  summary {
    color: #5a7a94;
    cursor: pointer;
    font-size: 0.85rem;
    padding: 0.3rem 0;
  }
  summary:hover { color: #c8d6e5; }
  table { width: 100%; border-collapse: collapse; margin-top: 0.5rem; font-size: 0.85rem; }
  th, td { padding: 0.5rem 0.75rem; text-align: left; border-bottom: 1px solid #1a2332; }
  th { color: #5ce0d8; font-weight: 600; }
  .timeline { margin-top: 1rem; }
  .timeline h2 {
    color: #e2e8f0;
    font-size: 1.2rem;
    margin-bottom: 1rem;
    padding-bottom: 0.5rem;
    border-bottom: 1px solid #1e2d3d;
  }
  .dot {
    display: inline-block;
    width: 8px;
    height: 8px;
    border-radius: 50%;
    margin-right: 0.5rem;
    vertical-align: middle;
  }
  .footer {
    text-align: center;
    padding: 2rem;
    color: #3a4a5a;
    font-size: 0.8rem;
    border-top: 1px solid #1e2d3d;
    margin-top: 2rem;
  }
</style>
</head>
<body>
<div class="header">
  <h1>EX NIHILO</h1>
  <div class="subtitle">Scheduled Pipeline Reports &mdash; Auto-refreshes every 60s</div>
</div>
<div class="container">
  <div class="grid">
    ${pipelineCards}
  </div>
  ${allReports.length > 0 ? `
  <div class="timeline">
    <h2>Recent Activity</h2>
    <table>
      <thead><tr><th>Pipeline</th><th>Report</th><th>Size</th><th>Generated</th></tr></thead>
      <tbody>${timelineRows}</tbody>
    </table>
  </div>` : ''}
</div>
<div class="footer">
  Meridian Logic Ltd &mdash; Ex Nihilo Pipeline Dashboard &mdash; Last refreshed: ${new Date().toISOString()}
</div>
</body>
</html>`;
}

// ── HTTP server ────────────────────────────────────────────────────────
const MIME = { '.html': 'text/html', '.css': 'text/css', '.js': 'application/javascript', '.json': 'application/json' };

function serveDashboard(res) {
  const html = renderDashboard();
  res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
  res.end(html);
}

function serveFile(res, filePath) {
  const resolved = path.resolve(filePath);
  // Prevent path traversal outside reports directory
  if (!resolved.startsWith(REPORTS_DIR)) {
    res.writeHead(403);
    res.end('Forbidden');
    return;
  }
  if (!fs.existsSync(resolved) || fs.statSync(resolved).isDirectory()) {
    res.writeHead(404, { 'Content-Type': 'text/html' });
    res.end('<h1>404 Not Found</h1>');
    return;
  }
  const ext = path.extname(resolved);
  const mime = MIME[ext] || 'application/octet-stream';
  const content = fs.readFileSync(resolved);
  res.writeHead(200, { 'Content-Type': `${mime}; charset=utf-8` });
  res.end(content);
}

const server = http.createServer((req, res) => {
  const url = decodeURIComponent(req.url.split('?')[0]);
  if (url === '/' || url === '/index.html') {
    serveDashboard(res);
  } else {
    serveFile(res, path.join(REPORTS_DIR, url));
  }
});

// ── Start ──────────────────────────────────────────────────────────────
gitPull();
setInterval(gitPull, PULL_INTERVAL);

server.listen(PORT, '0.0.0.0', () => {
  console.log(`Ex Nihilo Reports Dashboard: http://0.0.0.0:${PORT}`);
  console.log(`Git pull interval: ${PULL_INTERVAL / 1000}s`);
  console.log(`Serving reports from: ${REPORTS_DIR}`);
});
