/**
 * Ship design engine — pure functions for designing, validating, and
 * instantiating ships from hull templates and components.
 *
 * All functions are side-effect free. Callers are responsible for persisting
 * any state changes returned from these functions.
 */

import type { HullTemplate, ShipComponent, ShipDesign, Ship, ComponentType, SlotPosition } from '../types/ships.js';
import { getEffectiveHullPoints, getEffectiveCost } from '../types/ships.js';
import { generateId } from '../utils/id.js';
import { TECH_AGES } from '../constants/game.js';
import { HULL_TEMPLATES, SHIP_COMPONENT_BY_ID } from '../../data/ships/index.js';

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface DesignStats {
  totalDamage: number;
  totalShields: number;
  totalArmor: number;
  speed: number;
  sensorRange: number;
  repairRate: number;
  cost: number;
  /** Effective hull points after armour plating. */
  effectiveHullPoints: number;
  /** Accuracy bonus from targeting computers. */
  accuracyBonus: number;
  /** Evasion bonus from ECM suites. */
  evasionBonus: number;
  /** Total power generated by engines. */
  powerOutput: number;
  /** Total power consumed by all systems. */
  powerDraw: number;
  /** Power buffer from batteries/capacitors. */
  powerBuffer: number;
  /** Net power balance (output + buffer - draw). Negative = underpowered. */
  powerBalance: number;
  /** Crew complement from hull template. */
  crewCount: number;
  /** Supply capacity in turns (hull base + bio reclamation bonus). */
  supplyCapacity: number;
  /** Estimated mass: hull mass + component mass + armour mass. */
  mass: number;
  /** Whether this design requires a crew. Unmanned hulls (probes) are false. */
  manned: boolean;
}

export interface ValidationResult {
  valid: boolean;
  errors: string[];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Size ordering: small < medium < large */
const SIZE_ORDER: Record<SlotPosition['size'], number> = {
  small: 1,
  medium: 2,
  large: 3,
};

/**
 * Returns true if a component of the given size fits in a slot of slotSize.
 * Components can only fit in slots of their exact size or larger.
 */
function componentFitsSize(
  componentSize: SlotPosition['size'],
  slotSize: SlotPosition['size'],
): boolean {
  return SIZE_ORDER[componentSize] <= SIZE_ORDER[slotSize];
}

/**
 * Infer the minimum required slot size for a component based on its type and
 * stats. This is a heuristic used by autoEquipDesign.
 *
 * The rules are kept simple:
 *  - fighter_bay → large
 *  - engine/warp_drive with speed > 5 → medium
 *  - everything else → small
 */
function inferComponentSize(component: ShipComponent): SlotPosition['size'] {
  if (component.type === 'fighter_bay') return 'large';
  if (
    (component.type === 'engine' || component.type === 'warp_drive') &&
    (component.stats['speed'] ?? 0) > 5
  ) {
    return 'medium';
  }
  return 'small';
}

// ---------------------------------------------------------------------------
// validateDesign
// ---------------------------------------------------------------------------

/**
 * Validates a ShipDesign against its hull template and the set of components
 * assigned to it.
 *
 * Checks:
 *  1. Every slot assignment references a valid slot on the hull.
 *  2. No slot is assigned more than once.
 *  3. Each component type is allowed in its assigned slot.
 *  4. The design contains at least one engine component.
 *  5. All component IDs can be resolved in the provided components array.
 *  6. Component fits the slot size.
 */
export function validateDesign(
  design: ShipDesign,
  hull: HullTemplate,
  components: ShipComponent[],
): ValidationResult {
  const errors: string[] = [];

  const componentById = new Map(components.map((c) => [c.id, c]));
  const slotById = new Map(hull.slotLayout.map((s) => [s.id, s]));

  const usedSlotIds = new Set<string>();
  let hasEngine = false;

  for (const assignment of design.components) {
    const slot = slotById.get(assignment.slotId);
    if (!slot) {
      errors.push(
        `Slot "${assignment.slotId}" does not exist on hull "${hull.class}".`,
      );
      continue;
    }

    if (usedSlotIds.has(assignment.slotId)) {
      errors.push(`Slot "${assignment.slotId}" is assigned more than once.`);
    }
    usedSlotIds.add(assignment.slotId);

    const component = componentById.get(assignment.componentId);
    if (!component) {
      errors.push(
        `Component "${assignment.componentId}" not found in the provided component list.`,
      );
      continue;
    }

    if (!(slot.allowedTypes as ComponentType[]).includes(component.type)) {
      errors.push(
        `Component "${component.name}" (type: ${component.type}) is not allowed in slot "${slot.id}" (allowed: ${slot.allowedTypes.join(', ')}).`,
      );
    }

    const requiredSize = inferComponentSize(component);
    if (!componentFitsSize(requiredSize, slot.size)) {
      errors.push(
        `Component "${component.name}" requires at least a ${requiredSize} slot, but slot "${slot.id}" is ${slot.size}.`,
      );
    }

    if (component.type === 'engine' || component.type === 'warp_drive') {
      hasEngine = true;
    }
  }

  if (!hasEngine) {
    errors.push('Design has no engine or warp drive — the ship cannot move.');
  }

  // Validate armour plating range
  const ap = design.armourPlating ?? 0;
  if (ap < 0 || ap > 1) {
    errors.push(`Armour plating must be between 0 and 1 (got ${ap}).`);
  }

  // Power budget check (warp drives excluded — not active during combat)
  let powerOut = 0;
  let powerDraw = 0;
  let powerBuf = 0;
  for (const a of design.components) {
    const c = componentById.get(a.componentId);
    if (!c) continue;
    if (c.type === 'engine') {
      powerOut += c.stats['powerOutput'] ?? 0;
    } else if (c.type !== 'warp_drive') {
      powerDraw += c.stats['powerDraw'] ?? 0;
    }
    powerBuf += c.stats['powerBuffer'] ?? 0;
  }
  if (powerOut + powerBuf < powerDraw) {
    errors.push(`Power deficit: combat systems draw ${powerDraw} but engines output ${powerOut} + ${powerBuf} buffer. Ship will be underpowered.`);
  }

  return { valid: errors.length === 0, errors };
}

// ---------------------------------------------------------------------------
// calculateDesignStats
// ---------------------------------------------------------------------------

/**
 * Aggregate combat and utility statistics across all components in a design.
 *
 * Speed is the maximum speed value found across all engine components.
 * Sensor range is the maximum range across all sensor components.
 * All damage, shield, armor, and repair values are summed.
 * Cost includes the hull base cost plus all component costs, modified by armour plating.
 * Effective hull points factor in armour plating.
 */
export function calculateDesignStats(
  design: ShipDesign,
  hull: HullTemplate,
  components: ShipComponent[],
): DesignStats {
  const componentById = new Map(components.map((c) => [c.id, c]));
  const ap = design.armourPlating ?? 0;

  const stats: DesignStats = {
    totalDamage: 0,
    totalShields: 0,
    totalArmor: 0,
    speed: 0,
    sensorRange: 0,
    repairRate: 0,
    cost: getEffectiveCost(hull.baseCost, ap),
    effectiveHullPoints: getEffectiveHullPoints(hull.baseHullPoints, ap),
    accuracyBonus: 0,
    evasionBonus: 0,
    powerOutput: 0,
    powerDraw: 0,
    powerBuffer: 0,
    powerBalance: 0,
    crewCount: hull.baseCrew ?? 0,
    supplyCapacity: hull.baseSupplyCapacity ?? 15,
    mass: hull.baseHullPoints * 10,
    manned: hull.manned !== false,
  };

  for (const assignment of design.components) {
    const component = componentById.get(assignment.componentId);
    if (!component) continue;

    stats.cost += component.cost;

    // Accumulate power: engines generate, everything else consumes.
    // Warp drives are excluded from combat power draw — you don't warp and fight simultaneously.
    if (component.type === 'engine') {
      stats.powerOutput += component.stats['powerOutput'] ?? 0;
    } else if (component.type !== 'warp_drive') {
      stats.powerDraw += component.stats['powerDraw'] ?? 0;
    }

    // Accumulate power buffer from batteries/capacitors
    if (component.stats['powerBuffer']) {
      stats.powerBuffer += component.stats['powerBuffer'];
    }

    switch (component.type) {
      case 'weapon_beam':
      case 'weapon_projectile':
      case 'weapon_missile':
      case 'weapon_point_defense':
        stats.totalDamage += component.stats['damage'] ?? 0;
        break;

      case 'fighter_bay':
        stats.totalDamage +=
          (component.stats['fighterCount'] ?? 0) * (component.stats['damage'] ?? 0);
        break;

      case 'shield':
        stats.totalShields += component.stats['shieldStrength'] ?? 0;
        break;

      case 'armor':
        stats.totalArmor += component.stats['armorRating'] ?? 0;
        break;

      case 'engine':
        stats.speed = Math.max(stats.speed, component.stats['speed'] ?? 0);
        break;

      case 'warp_drive':
        if (stats.speed === 0) {
          stats.speed = Math.max(stats.speed, component.stats['warpSpeed'] ?? 0);
        }
        break;

      case 'sensor':
      case 'advanced_sensors':
      case 'scanner':
        stats.sensorRange = Math.max(stats.sensorRange, component.stats['sensorRange'] ?? 0);
        // Scanner components may also grant a range bonus (e.g. deep_space_telescope)
        if (component.stats['sensorRangeBonus']) {
          stats.sensorRange += component.stats['sensorRangeBonus'];
        }
        break;

      case 'repair_drone':
      case 'damage_control':
        stats.repairRate += component.stats['repairRate'] ?? 0;
        break;

      case 'targeting_computer':
        stats.accuracyBonus += component.stats['accuracyBonus'] ?? 0;
        break;

      case 'ecm_suite':
        stats.evasionBonus += component.stats['evasionBonus'] ?? 0;
        break;

      case 'life_support':
      case 'special':
        break;
    }
  }

  // Accumulate mass from slot components (each component's cost * 0.1 as a proxy)
  for (const assignment of design.components) {
    const component = componentById.get(assignment.componentId);
    if (!component) continue;
    stats.mass += component.cost * 0.1;
  }

  // Accumulate armour mass (armour plating adds hull mass proportional to fraction)
  stats.mass += hull.baseHullPoints * 10 * ap * 2;

  // Core system overrides — accumulate stat bonuses from upgraded tiers
  if (design.coreSystemOverrides) {
    for (const override of design.coreSystemOverrides) {
      const comp = SHIP_COMPONENT_BY_ID[override.componentId] ?? componentById.get(override.componentId);
      if (!comp) continue;

      // All core systems may draw power
      stats.powerDraw += comp.stats['powerDraw'] ?? 0;

      // Add cost and mass contribution
      stats.cost += comp.cost;
      stats.mass += comp.cost * 0.1;

      switch (override.role) {
        case 'power_reactor':
          stats.powerOutput += comp.stats['powerOutput'] ?? 0;
          break;
        case 'rcs_thrusters':
          stats.evasionBonus += comp.stats['evasionBonus'] ?? 0;
          break;
        case 'computer_core':
          stats.accuracyBonus += comp.stats['accuracyBonus'] ?? 0;
          break;
        case 'bio_reclamation':
          stats.supplyCapacity += comp.stats['supplyBonus'] ?? 0;
          break;
        case 'main_engine':
          stats.speed = Math.max(stats.speed, comp.stats['speed'] ?? 0);
          stats.powerOutput += comp.stats['powerOutput'] ?? 0;
          break;
        default:
          // sensor_suite, life_support, temperature_control, comms_array
          // — stat bonuses handled via their component type in the slot loop above
          break;
      }
    }
  }

  // Apply hull base speed as a floor if no engine was fitted
  if (stats.speed === 0) {
    stats.speed = hull.baseSpeed;
  }

  // Round mass to nearest integer for display
  stats.mass = Math.round(stats.mass);

  // Calculate net power balance
  stats.powerBalance = stats.powerOutput + stats.powerBuffer - stats.powerDraw;

  return stats;
}

// ---------------------------------------------------------------------------
// createShipFromDesign
// ---------------------------------------------------------------------------

/**
 * Instantiate a new Ship from a completed ShipDesign.
 * The ship starts undamaged, not assigned to a fleet, at the given system.
 * Hull points are modified by the design's armour plating.
 */
export function createShipFromDesign(
  design: ShipDesign,
  hull: HullTemplate,
  empireId: string,
  systemId: string,
): Ship {
  const hp = getEffectiveHullPoints(hull.baseHullPoints, design.armourPlating ?? 0);
  const isManned = hull.manned !== false;
  const baseSupply = hull.baseSupplyCapacity ?? 15;

  // Compute supply bonus from bio reclamation core system overrides
  let supplyBonus = 0;
  if (design.coreSystemOverrides) {
    for (const override of design.coreSystemOverrides) {
      if (override.role === 'bio_reclamation') {
        const comp = SHIP_COMPONENT_BY_ID[override.componentId];
        if (comp) supplyBonus += comp.stats['supplyBonus'] ?? 0;
      }
    }
  }

  const maxSupplies = baseSupply + supplyBonus;

  return {
    id: generateId(),
    designId: design.id,
    name: design.name,
    hullPoints: hp,
    maxHullPoints: hp,
    systemDamage: {
      engines: 0,
      weapons: 0,
      shields: 0,
      sensors: 0,
      warpDrive: 0,
    },
    position: { systemId },
    fleetId: null,
    suppliesRemaining: isManned ? maxSupplies : undefined,
    maxSupplies: isManned ? maxSupplies : undefined,
    magazineLevel: 1.0,
    crewCount: hull.baseCrew ?? 0,
  };
}

// ---------------------------------------------------------------------------
// getAvailableComponents
// ---------------------------------------------------------------------------

/**
 * Filter the full component list to those available to an empire given the
 * set of technology IDs it has researched.
 *
 * Components with requiredTech === null are always available.
 */
export function getAvailableComponents(
  allComponents: ShipComponent[],
  researchedTechs: string[],
): ShipComponent[] {
  const techSet = new Set(researchedTechs);
  return allComponents.filter(
    (c) => c.requiredTech === null || techSet.has(c.requiredTech),
  );
}

// ---------------------------------------------------------------------------
// autoEquipDesign
// ---------------------------------------------------------------------------

/**
 * Automatically fill all slots on a hull with the best available components.
 *
 * Priority per slot (first allowedType wins):
 *  1. If only one allowed type, pick the best component of that type.
 *  2. Weapon slots prefer the highest-damage component.
 *  3. Engine/warp_drive slots prefer the highest-speed component.
 *  4. Shield slots prefer the highest shieldStrength.
 *  5. Armor slots prefer the highest armorRating.
 *  6. Sensor/internal slots — best by relevant stat.
 *
 * The returned ShipDesign has a generated ID, uses the hull's class, and
 * starts with an empty empireId (caller should override before persisting).
 */
export function autoEquipDesign(
  hull: HullTemplate,
  availableComponents: ShipComponent[],
): ShipDesign {
  const assignments: { slotId: string; componentId: string }[] = [];

  // Track weapon slot index to vary weapon types for a diverse loadout
  let weaponSlotIdx = 0;
  const WEAPON_TYPE_ROTATION: ComponentType[] = [
    'weapon_beam', 'weapon_projectile', 'weapon_missile',
    'weapon_beam', 'weapon_projectile', 'weapon_missile',
  ];

  for (const slot of hull.slotLayout) {
    // Collect components that are allowed in this slot and physically fit
    const candidates = availableComponents.filter((c) => {
      if (!(slot.allowedTypes as ComponentType[]).includes(c.type)) return false;
      return componentFitsSize(inferComponentSize(c), slot.size);
    });

    if (candidates.length === 0) continue;

    // For weapon slots: rotate through beam → projectile → missile for variety
    let priorityType = slot.allowedTypes[0] as ComponentType;
    if (slot.category === 'weapon') {
      const preferred = WEAPON_TYPE_ROTATION[weaponSlotIdx % WEAPON_TYPE_ROTATION.length]!;
      // Only use preferred if the slot accepts it
      if ((slot.allowedTypes as ComponentType[]).includes(preferred)) {
        priorityType = preferred;
      }
      weaponSlotIdx++;
    }

    // Pick best component by priority type, then fall back to any candidate
    const best = pickBestComponent(candidates, priorityType);
    if (best) {
      assignments.push({ slotId: slot.id, componentId: best.id });
    }
  }

  // Set sensible armour plating defaults by hull class — heavier hulls get more
  const ARMOUR_DEFAULTS: Record<string, number> = {
    battleship: 0.3,
    dreadnought: 0.3,
    battle_station: 0.3,
    cruiser: 0.2,
    carrier: 0.2,
    destroyer: 0.1,
    transport: 0.1,
    scout: 0.0,
    coloniser: 0.0,
    deep_space_probe: 0.0,
  };
  const armourPlating = ARMOUR_DEFAULTS[hull.class] ?? 0;

  return {
    id: generateId(),
    name: `Auto-${hull.name}`,
    hull: hull.class,
    components: assignments,
    totalCost: 0, // caller should recalculate with calculateDesignStats
    empireId: '',
    armourPlating,
  };
}

/** Pick the single best component from a list, biased toward the given type. */
function pickBestComponent(
  candidates: ShipComponent[],
  preferredType: ComponentType,
): ShipComponent | undefined {
  // Prefer components of the preferred type; fall back to all candidates
  const typed = candidates.filter((c) => c.type === preferredType);
  const pool = typed.length > 0 ? typed : candidates;

  return pool.reduce<ShipComponent | undefined>((best, c) => {
    if (!best) return c;
    return scoreComponent(c, preferredType) > scoreComponent(best, preferredType) ? c : best;
  }, undefined);
}

/** Assign a numeric score to a component for auto-equip sorting. */
function scoreComponent(component: ShipComponent, forType: ComponentType): number {
  const s = component.stats;
  switch (forType) {
    case 'weapon_beam':
    case 'weapon_projectile':
    case 'weapon_missile':
    case 'weapon_point_defense':
      return (s['damage'] ?? 0) + (s['range'] ?? 0) * 0.5;

    case 'fighter_bay':
      return (s['fighterCount'] ?? 0) * (s['damage'] ?? 0);

    case 'shield':
      return (s['shieldStrength'] ?? 0) + (s['rechargeRate'] ?? 0) * 2;

    case 'armor':
      return s['armorRating'] ?? 0;

    case 'engine':
      return s['speed'] ?? 0;

    case 'warp_drive':
      return (s['warpSpeed'] ?? 0) + (s['warpRange'] ?? 0) * 0.5;

    case 'sensor':
    case 'advanced_sensors':
    case 'scanner':
      return (s['sensorRange'] ?? 0) + (s['sensorRangeBonus'] ?? 0) + (s['detectionBonus'] ?? 0) * 0.3 + (s['scanAccuracy'] ?? 0) * 0.1;

    case 'repair_drone':
    case 'damage_control':
      return s['repairRate'] ?? 0;

    case 'targeting_computer':
      return s['accuracyBonus'] ?? 0;

    case 'ecm_suite':
      return s['evasionBonus'] ?? 0;

    case 'life_support':
      return (s['moraleRecovery'] ?? 0) + (s['crewCapacity'] ?? 0) * 0.1;

    case 'special':
      // No dominant stat for 'special'; fall back to cost as a quality proxy
      return component.cost;

    case 'power_reactor':
      return s['powerOutput'] ?? 0;

    case 'rcs_thrusters':
      return (s['evasionBonus'] ?? 0) + (s['turnRate'] ?? 0);

    case 'temperature_control':
      return s['heatDissipation'] ?? 0;

    case 'comms_array':
      return (s['signalRange'] ?? 0) + (s['commsBonus'] ?? 0) * 0.3;

    case 'bio_reclamation':
      return (s['supplyBonus'] ?? 0) + (s['waterRecycling'] ?? 0) * 0.1;

    case 'computer_core':
      return (s['processingPower'] ?? 0) + (s['accuracyBonus'] ?? 0);
  }
}

// ---------------------------------------------------------------------------
// generateDefaultDesigns
// ---------------------------------------------------------------------------

/**
 * Generate default ship designs for all hull types available at the given age
 * that don't already have a design in the provided map.
 */
export function generateDefaultDesigns(
  currentAge: string,
  empireId: string,
  existingDesigns: Map<string, ShipDesign>,
  availableComponents: ShipComponent[],
): ShipDesign[] {
  const ageIdx = TECH_AGES.findIndex(a => a.name === currentAge);
  const newDesigns: ShipDesign[] = [];

  for (const hull of HULL_TEMPLATES) {
    const hullAgeIdx = TECH_AGES.findIndex(a => a.name === hull.requiredAge);
    if (hullAgeIdx < 0 || hullAgeIdx > ageIdx) continue;

    // Check if a design already exists for this hull class
    const alreadyHasDesign = Array.from(existingDesigns.values()).some(
      d => d.hull === hull.class && d.empireId === empireId,
    );
    if (alreadyHasDesign) continue;

    const design = autoEquipDesign(hull, availableComponents);
    design.id = `default-${hull.class}-${empireId}`;
    design.name = hull.name;
    design.empireId = empireId;
    // Calculate total cost (with armour plating = 0)
    const stats = calculateDesignStats(design, hull, availableComponents);
    design.totalCost = stats.cost;

    newDesigns.push(design);
  }

  return newDesigns;
}

// ---------------------------------------------------------------------------
// Warp drive helpers
// ---------------------------------------------------------------------------

/**
 * Returns true if the given ship design includes a warp_drive component.
 * Ships without a warp drive cannot travel between star systems unless carried.
 */
export function designHasWarpDrive(
  design: ShipDesign,
  components: ShipComponent[],
): boolean {
  const componentById = new Map(components.map((c) => [c.id, c]));
  return design.components.some(a => {
    const comp = componentById.get(a.componentId);
    return comp?.type === 'warp_drive';
  });
}
